### ISSUE TITLE
文字超出时才显示tooltip

### ISSUE THREAD

**Issue by qiulijun9** [qiulijun9/Q-A#28]
项目中有这样的场景经常会使用到  文字超出一行（或一定宽度）时显示… hover 显示 tooltip

如何实现这样的tooltip ?

可以定义一个影子节点，来判断实际显示的文字和影子节点的宽度来决定是否显示tooltip

影子节点不在文档流中，亦不可操作。

```jsx

const AutoTooltip = ({ content, placement, children, style, maxWidth }) => {
  const [showTooltip, setShowTooltip] = useState(false);
  const autoTooltipCompRef = useRef();
  const autoTooltipShadowRef = useRef();

  useEffect(() => {
    const { offsetWidth: compOffsetWidth } = autoTooltipCompRef.current || {};
    const { offsetWidth: shadowOffsetWidth } = autoTooltipShadowRef.current || {};
     // 判断是否显示tooltip
    setShowTooltip(compOffsetWidth < shadowOffsetWidth);
  }, [children, content]);

  function handleShowToolTip(e) {
    if (!showTooltip) {
      e.target.style.pointerEvents = 'none'; // 阻止鼠标事件
    }
  }
  return (
    <Tooltip
      title={content}
      placement={placement}
      onMouseEnter={() => handleShowToolTip()}
    >
      <div
        ref={autoTooltipCompRef}
        className={styles.autoTooltipContainer}
      >
        <div
          className={styles['auto-tooltip-title']}
          style={{
            maxWidth,
          }}
        >
          {content || children}
        </div>

        <div ref={autoTooltipShadowRef} className={styles['auto-tooltip-title-shadow']}>
          {content || children}
        </div>
      </div>
    </Tooltip>
  );
};

```

css

```css
.autoTooltipContainer {
  box-sizing: border-box;
  position: relative;
  display: flex;
  align-items: center;
  overflow: hidden;
}

.auto-tooltip-title {
  box-sizing: border-box;
  overflow: hidden;
  text-overflow: ellipsis;
}

.auto-tooltip-title-shadow {
  box-sizing: border-box;
  position: absolute;
  top: 0;
  left: 0;
  opacity: 0;
  user-select: none;
}
```
